/* function C pshell address */
.equ printf,             0x1000ac85
.equ getchar,            0x100240c5
.equ putchar,            0x10023d7d
.equ exit,               0x1000a3ad
.equ getchar_timeout_us, 0x10024139
.equ open,               0x1000b2b1
.equ write,              0x1000a561
.equ read,               0x1000a761
.equ close,              0x1000af79
.equ lssek,              0x1000a491
